apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rearc-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{.Values.ingress.host}}
      secretName: {{.Values.ingress.secretname}}
  rules:
    - host: {{.Values.ingress.host}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rearc-service
                port:
                  number: 80
