apiVersion: apps/v1
kind: Deployment
metadata:
  name: rearc-app
  labels:
    app: rearc-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rearc-app
  template:
    metadata:
      labels:
        app: rearc-app
    spec:
      {{- include "quest.app.pod-security-context" . | nindent 6 }}
      containers:
        - name: rearc-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 3000
          env:
            - name: SECRET_WORD
              valueFrom:
                secretKeyRef:
                  name: rearc-secrets
                  key: secret_word

